import { Show } from "./types";

export const movieData: Show[] = [
  {
    id: 1,
    name: "INTERSTELLAR",
    adult: false,
    overview:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    originalLanguage: "en",
    posterPath: "/interstellar_card.jpg",
    backdropPath: "/interstellar_backdrop.jpg",
    alt: "Interstellar movie poster",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    voteAverage: 4.7,
  },
  {
    id: 2,
    name: "INCEPTION",
    adult: false,
    overview:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    originalLanguage: "en",
    posterPath: "/inception_card.jpeg",
    backdropPath: "/inception_backdrop.jpg",
    alt: "Inception movie poster",
    genres: ["Action", "Sci-Fi", "Thriller"],
    voteAverage: 4.8,
  },
  {
    id: 3,
    name: "THE MATRIX",
    adult: false,
    overview:
      "A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to break free from the system.",
    originalLanguage: "en",
    posterPath: "/the-matrix_card.webp",
    backdropPath: "/the-matrix_backdrop.jpg",
    alt: "The Matrix movie poster",
    genres: ["Action", "Sci-Fi"],
    voteAverage: 4.9,
  },
  {
    id: 4,
    name: "PARASITE",
    adult: false,
    overview:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    originalLanguage: "ko",
    posterPath: "/parasite_card.webp",
    backdropPath: "/parasite_backdrop.jpg",
    alt: "Parasite movie poster",
    genres: ["Drama", "Thriller"],
    voteAverage: 4.6,
  },
  {
    id: 5,
    name: "THE LAST OF US",
    adult: false,
    overview:
      "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
    originalLanguage: "en",
    posterPath: "/the-last-of-us_card.webp",
    backdropPath: "/the-last-of-us_backdrop.jpg",
    alt: "The Last of Us series poster",
    genres: ["Drama", "Action", "Horror"],
    voteAverage: 4.7,
  },
  {
    id: 6,
    name: "BLACK MIRROR",
    adult: false,
    overview:
      "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
    originalLanguage: "en",
    posterPath: "/black-mirror_card.webp",
    backdropPath: "/black-mirror_backdrop.jpg",
    alt: "Black Mirror series poster",
    genres: ["Sci-Fi", "Drama", "Thriller"],
    voteAverage: 4.5,
  },
  {
    id: 7,
    name: "DAREDEVIL",
    adult: false,
    overview:
      "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.",
    originalLanguage: "en",
    posterPath: "/daredevil_card.webp",
    backdropPath: "/daredevil_backdrop.jpg",
    alt: "Daredevil series poster",
    genres: ["Action", "Crime", "Drama"],
    voteAverage: 4.6,
  },
  {
    id: 8,
    name: "JUSTICE LEAGUE",
    adult: false,
    overview:
      "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world.",
    originalLanguage: "en",
    posterPath: "/justice-league_card.jpg",
    backdropPath: "/justice-league_backdrop.jpg",
    alt: "Justice League movie poster",
    genres: ["Action", "Adventure", "Fantasy"],
    voteAverage: 4.3,
  },
];
